import os
import subprocess
import yaml # pip install pyyaml

# [설정] 룰 파일이 모여있는 폴더 이름 (프로젝트 구조에 맞춤)
RULE_DIR = "rules" 
OUTPUT_FILE = "savedsearches.conf"

def run_pipeline():
    print("🚀 [Scenario] Incident Generator Pipeline 시작...")
    
    # rules 폴더가 있는지 확인
    if not os.path.exists(RULE_DIR):
        print(f"❌ Error: '{RULE_DIR}' 폴더를 찾을 수 없습니다. 현재 위치: {os.getcwd()}")
        exit(1) # 강제 실패 처리

    # yml 파일 찾기
    yml_files = [f for f in os.listdir(RULE_DIR) if f.endswith('.yml')]
    
    if not yml_files:
        print(f"⚠️ 경고: '{RULE_DIR}' 폴더에 .yml 파일이 없습니다.")
        # 파일이 없어도 CI/CD가 죽지 않게 빈 파일이라도 생성하려면 아래 주석 해제
        # open(OUTPUT_FILE, 'w').close()
        exit(1) # 지금은 실습이니 파일 없으면 에러로 처리

    print(f"📦 발견된 룰 파일: {len(yml_files)}개")
    
    with open(OUTPUT_FILE, 'w') as outfile:
        outfile.write("# Generated by Detection-as-Code Pipeline\n")
        outfile.write("# Creates Incidents in 'index=incidents'\n\n")

        for yml in yml_files:
            # [중요] 파일명만 있으면 안 되고, 경로까지 합쳐야 함!
            full_path = os.path.join(RULE_DIR, yml)
            
            try:
                # 1. 메타데이터 읽기
                with open(full_path, 'r') as f:
                    rule_content = yaml.safe_load(f)
                
                title = rule_content.get('title', 'Untitled Rule')
                description = rule_content.get('description', 'No description')
                
                # 2. Sigma 변환 (경로 포함해서 실행)
                cmd = ["sigma", "convert", "-t", "splunk", "--without-pipeline", full_path]
                
                result = subprocess.run(cmd, capture_output=True, text=True, check=True)
                query = result.stdout.strip()
                
                # 3. Splunk 설정 작성
                stanza = f"""
[{title}]
search = {query}
description = {description}
enable_sched = 1
cron_schedule = * * * * *
dispatch.earliest_time = -5m
dispatch.latest_time = now
action.summary_index = 1
action.summary_index._name = incidents
action.summary_index.report = {title}
alert.severity = 4
disabled = 0
"""
                outfile.write(stanza + "\n")
                print(f"✅ Created Scenario: {title}")
                
            except subprocess.CalledProcessError as e:
                print(f"❌ Sigma 변환 실패 ({yml}): {e.stderr}")
                exit(1) # 변환 실패 시 CI 중단
            except Exception as e:
                print(f"❌ 일반 에러 ({yml}): {e}")
                exit(1)

    print(f"\n✨ [Success] '{OUTPUT_FILE}' 생성 완료!")

if __name__ == "__main__":
    run_pipeline()